"""empty message

Revision ID: f7c740b08eb3
Revises: 1cb83c2a2474
Create Date: 2024-04-28 20:09:32.894839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c740b08eb3'
down_revision = '1cb83c2a2474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_attendance', ['user', 'attendance_date', 'status'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('unique_attendance', type_='unique')

    # ### end Alembic commands ###
